import { useState, useEffect } from "react";

const C = {
  bg: "#f5f0e8",
  surface: "#fffdf7",
  card: "#ffffff",
  border: "#1a1a1a",
  accent: "#ff3c00",
  accentDark: "#cc3000",
  accentLight: "#fff0eb",
  green: "#00a651",
  yellow: "#ffbe00",
  yellowLight: "#fffbe6",
  blue: "#0057ff",
  red: "#ff3c00",
  textPrimary: "#0d0d0d",
  textSecondary: "#4a4a4a",
  textMuted: "#9a9a9a",
};

function Btn({ children, onClick, primary, small, disabled, full }) {
  const [h, setH] = useState(false);
  return (
    <button
      disabled={disabled}
      onClick={onClick}
      onMouseEnter={() => setH(true)}
      onMouseLeave={() => setH(false)}
      style={{
        padding: small ? "9px 20px" : "14px 32px",
        borderRadius: 6,
        fontSize: small ? 13 : 15,
        fontWeight: 700,
        cursor: disabled ? "not-allowed" : "pointer",
        fontFamily: "inherit",
        border: "2px solid " + C.border,
        background: primary ? (h ? C.accentDark : C.accent) : (h ? "#eee" : C.card),
        color: primary ? "#fff" : C.textPrimary,
        boxShadow: h ? "2px 2px 0 #0d0d0d" : "4px 4px 0 #0d0d0d",
        transform: h ? "translate(2px,2px)" : "none",
        width: full ? "100%" : "auto",
        opacity: disabled ? 0.45 : 1,
      }}
    >
      {children}
    </button>
  );
}

function Box({ children, style }) {
  return (
    <div
      style={{
        background: C.card,
        border: "2px solid " + C.border,
        borderRadius: 8,
        padding: "20px 22px",
        boxShadow: "4px 4px 0 #0d0d0d",
        ...style,
      }}
    >
      {children}
    </div>
  );
}

function Bar({ value, color, height }) {
  return (
    <div style={{ height: height || 6, background: "#e8e3d8", borderRadius: 2, overflow: "hidden" }}>
      <div style={{ height: "100%", width: value + "%", background: color || C.accent, transition: "width 0.7s ease" }} />
    </div>
  );
}

function Tag({ label, color }) {
  return (
    <span style={{
      fontSize: 10, fontWeight: 800, padding: "3px 10px", borderRadius: 3,
      background: (color || C.accent) + "18", color: color || C.accent,
      border: "1.5px solid " + (color || C.accent),
      letterSpacing: "0.08em", textTransform: "uppercase",
      display: "inline-block",
    }}>
      {label}
    </span>
  );
}

// ── NAVBAR ────────────────────────────────────────────────────
function Navbar({ setPage }) {
  return (
    <div style={{ background: C.textPrimary, borderBottom: "2px solid " + C.border, padding: "0 28px", position: "sticky", top: 0, zIndex: 100 }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", height: 54, maxWidth: 1100, margin: "0 auto" }}>
        <div onClick={() => setPage("landing")} style={{ display: "flex", alignItems: "center", gap: 10, cursor: "pointer" }}>
          <div style={{ width: 28, height: 28, borderRadius: 5, background: C.accent, border: "2px solid #fff", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 14 }}>🧪</div>
          <span style={{ fontSize: 17, fontWeight: 900, letterSpacing: "-0.04em", color: "#fff" }}>QualityZero</span>
        </div>
        <Btn small primary onClick={() => setPage("run")}>Start Free →</Btn>
      </div>
    </div>
  );
}

// ── LANDING ───────────────────────────────────────────────────
function Landing({ onStart }) {
  const [ticker, setTicker] = useState(3841);

  useEffect(() => {
    const t = setInterval(() => {
      setTicker((v) => v + Math.floor(Math.random() * 4 + 1));
    }, 2200);
    return () => clearInterval(t);
  }, []);

  const features = [
    ["🤖", "Browser Automation", "Replaces Selenium engineers — auto-generates and runs all UI tests"],
    ["⚡", "Performance Testing", "Load tests, stress tests, bottleneck detection at scale"],
    ["🔒", "Security / Pen Test", "OWASP Top 10, SQL injection, XSS, auth bypass, CSRF"],
    ["🧩", "Unit Testing", "Full function coverage with edge cases auto-generated by AI"],
    ["📱", "Mobile Testing", "iOS & Android simulation, gestures, offline mode, orientation"],
    ["🩹", "Self-Healing", "Broken tests auto-repaired when your UI changes — zero maintenance"],
  ];

  return (
    <div>
      {/* Hero */}
      <div style={{ borderBottom: "2px solid " + C.border, background: C.bg }}>
        <div style={{ maxWidth: 1000, margin: "0 auto", padding: "70px 28px 60px", display: "grid", gridTemplateColumns: "1fr 1fr", gap: 48, alignItems: "center" }}>
          <div>
            <div style={{ display: "inline-flex", alignItems: "center", gap: 8, background: C.yellowLight, border: "1.5px solid " + C.yellow, borderRadius: 4, padding: "5px 12px", marginBottom: 24 }}>
              <span style={{ fontSize: 13, fontWeight: 700, color: "#7a5a00" }}>🧪 {ticker.toLocaleString()} bugs crushed today</span>
            </div>
            <h1 style={{ fontSize: 52, fontWeight: 900, lineHeight: 1.05, letterSpacing: "-0.04em", color: C.textPrimary, marginBottom: 20 }}>
              Replace Every<br />
              <span style={{ color: C.accent }}>Automated</span><br />
              Tester. Now.
            </h1>
            <p style={{ fontSize: 17, color: C.textSecondary, lineHeight: 1.65, marginBottom: 32 }}>
              One URL. Three minutes. A complete audit replacing your entire QA automation team.
            </p>
            <div style={{ display: "flex", gap: 12 }}>
              <Btn primary onClick={onStart}>Start Free Testing →</Btn>
              <Btn onClick={onStart}>See Demo</Btn>
            </div>
          </div>

          {/* Terminal */}
          <div style={{ background: "#0d0d0d", border: "2px solid " + C.border, borderRadius: 8, padding: "20px 22px", boxShadow: "6px 6px 0 #0d0d0d", fontFamily: "monospace" }}>
            <div style={{ display: "flex", gap: 6, marginBottom: 14 }}>
              <div style={{ width: 12, height: 12, borderRadius: "50%", background: "#ff5f56" }} />
              <div style={{ width: 12, height: 12, borderRadius: "50%", background: "#ffbd2e" }} />
              <div style={{ width: 12, height: 12, borderRadius: "50%", background: "#27c93f" }} />
            </div>
            {[
              ["#9a9a9a", "$ qualityzero run https://acme.com"],
              ["#ffbe00", "→ Crawling 24 routes..."],
              ["#9a9a9a", "→ Generating 418 test cases..."],
              ["#00a651", "✓ 401 tests passed"],
              ["#ff3c00", "✗ 17 bugs found (2 critical)"],
              ["#0057ff", "⟳ 4 tests auto-healed"],
              ["#9a9a9a", "→ Report ready in 2m 41s"],
            ].map((item, i) => (
              <div key={i} style={{ fontSize: 13, color: item[0], lineHeight: 2 }}>{item[1]}</div>
            ))}
          </div>
        </div>
      </div>

      {/* Stats */}
      <div style={{ background: C.surface, borderBottom: "2px solid " + C.border }}>
        <div style={{ maxWidth: 1000, margin: "0 auto", padding: "0 28px", display: "grid", gridTemplateColumns: "repeat(4, 1fr)" }}>
          {[["99.4%", "Bug detection rate"], ["10×", "Faster than humans"], ["$0", "QA salaries needed"], ["<3min", "Full audit time"]].map((item, i) => (
            <div key={i} style={{ textAlign: "center", padding: "28px 16px", borderRight: i < 3 ? "2px solid " + C.border : "none" }}>
              <div style={{ fontSize: 36, fontWeight: 900, color: C.textPrimary }}>{item[0]}</div>
              <div style={{ fontSize: 12, color: C.textSecondary, marginTop: 4, fontWeight: 600 }}>{item[1]}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Features */}
      <div style={{ maxWidth: 1000, margin: "0 auto", padding: "60px 28px" }}>
        <h2 style={{ textAlign: "center", fontSize: 32, fontWeight: 900, color: C.textPrimary, marginBottom: 32 }}>Six roles. One tool.</h2>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 16 }}>
          {features.map((f) => (
            <Box key={f[1]}>
              <div style={{ fontSize: 26, marginBottom: 10 }}>{f[0]}</div>
              <div style={{ fontSize: 14, fontWeight: 800, color: C.textPrimary, marginBottom: 6 }}>{f[1]}</div>
              <div style={{ fontSize: 12, color: C.textSecondary, lineHeight: 1.6 }}>{f[2]}</div>
            </Box>
          ))}
        </div>
      </div>

      {/* CTA */}
      <div style={{ background: C.textPrimary, borderTop: "2px solid " + C.border, padding: "60px 28px", textAlign: "center" }}>
        <h2 style={{ fontSize: 30, fontWeight: 900, color: "#fff", marginBottom: 12 }}>Ready to cut your QA costs to zero?</h2>
        <p style={{ fontSize: 15, color: "#9a9a9a", marginBottom: 28 }}>Free forever for solo devs. No credit card. No BS.</p>
        <Btn primary onClick={onStart}>Start Free — Test Your App Now →</Btn>
      </div>
    </div>
  );
}

// ── CONFIGURE ─────────────────────────────────────────────────
function Configure({ onRun }) {
  const [mode, setMode] = useState("url");
  const [url, setUrl] = useState("");
  const [code, setCode] = useState("");
  const [depth, setDepth] = useState("full");
  const [types, setTypes] = useState({ browser: true, security: true, performance: true, unit: false, mobile: false });

  const testTypes = [
    ["browser", "🤖", "Browser Automation", "UI flows, forms, clicks, navigation"],
    ["security", "🔒", "Security / Pen Test", "OWASP Top 10, SQLi, XSS, CSRF"],
    ["performance", "⚡", "Load & Performance", "Stress test, latency, throughput"],
    ["unit", "🧩", "Unit Tests", "Function coverage, edge cases"],
    ["mobile", "📱", "Mobile Simulation", "iOS & Android, gestures, offline"],
  ];

  const canRun = mode === "url" ? url.trim().length > 4 : code.trim().length > 10;

  return (
    <div style={{ maxWidth: 680, margin: "0 auto", padding: "48px 28px" }}>
      <h2 style={{ fontSize: 28, fontWeight: 900, color: C.textPrimary, marginBottom: 4 }}>Configure Your Audit</h2>
      <p style={{ fontSize: 14, color: C.textSecondary, marginBottom: 28 }}>AI does everything. Just point it at your app.</p>

      <div style={{ display: "flex", gap: 8, marginBottom: 18 }}>
        {[["url", "🌐 Test a URL"], ["code", "📄 Upload Code"]].map((m) => (
          <button key={m[0]} onClick={() => setMode(m[0])}
            style={{ padding: "10px 20px", borderRadius: 6, fontSize: 13, fontWeight: 700, cursor: "pointer", fontFamily: "inherit", border: "2px solid " + (mode === m[0] ? C.accent : C.border), background: mode === m[0] ? C.accentLight : C.surface, color: mode === m[0] ? C.accent : C.textSecondary }}>
            {m[1]}
          </button>
        ))}
      </div>

      <Box style={{ marginBottom: 16 }}>
        {mode === "url" ? (
          <div>
            <label style={{ fontSize: 12, fontWeight: 800, color: C.textMuted, textTransform: "uppercase", display: "block", marginBottom: 8 }}>App URL</label>
            <input value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://your-app.com"
              style={{ width: "100%", background: C.bg, border: "2px solid " + C.border, borderRadius: 6, padding: "11px 14px", fontSize: 14, color: C.textPrimary, fontFamily: "inherit", outline: "none", boxSizing: "border-box" }} />
          </div>
        ) : (
          <div>
            <label style={{ fontSize: 12, fontWeight: 800, color: C.textMuted, textTransform: "uppercase", display: "block", marginBottom: 8 }}>Source Code</label>
            <textarea value={code} onChange={(e) => setCode(e.target.value)} rows={7} placeholder="// Paste JS, Python, Java..."
              style={{ width: "100%", background: C.bg, border: "2px solid " + C.border, borderRadius: 6, padding: "11px 14px", fontSize: 13, color: C.textPrimary, fontFamily: "monospace", outline: "none", resize: "vertical", boxSizing: "border-box" }} />
          </div>
        )}
      </Box>

      <Box style={{ marginBottom: 16 }}>
        <div style={{ fontSize: 12, fontWeight: 800, color: C.textMuted, textTransform: "uppercase", marginBottom: 14 }}>Testing Modules</div>
        {testTypes.map((t) => (
          <div key={t[0]} onClick={() => setTypes((p) => ({ ...p, [t[0]]: !p[t[0]] }))}
            style={{ display: "flex", alignItems: "center", gap: 12, padding: "10px 12px", borderRadius: 6, border: "2px solid " + (types[t[0]] ? C.accent : C.border), background: types[t[0]] ? C.accentLight : C.surface, cursor: "pointer", marginBottom: 8 }}>
            <span style={{ fontSize: 20 }}>{t[1]}</span>
            <div style={{ flex: 1 }}>
              <div style={{ fontSize: 13, fontWeight: 700, color: types[t[0]] ? C.accent : C.textPrimary }}>{t[2]}</div>
              <div style={{ fontSize: 11, color: C.textMuted }}>{t[3]}</div>
            </div>
            <div style={{ width: 18, height: 18, border: "2px solid " + (types[t[0]] ? C.accent : C.border), borderRadius: 4, background: types[t[0]] ? C.accent : "transparent", display: "flex", alignItems: "center", justifyContent: "center", color: "#fff", fontSize: 11, fontWeight: 800 }}>
              {types[t[0]] ? "✓" : ""}
            </div>
          </div>
        ))}
      </Box>

      <Box style={{ marginBottom: 28 }}>
        <div style={{ fontSize: 12, fontWeight: 800, color: C.textMuted, textTransform: "uppercase", marginBottom: 12 }}>Scan Depth</div>
        <div style={{ display: "flex", gap: 8 }}>
          {[["quick", "Quick", "~1 min"], ["full", "Full Audit", "~3 min"], ["deep", "Deep Dive", "~10 min"]].map((d) => (
            <div key={d[0]} onClick={() => setDepth(d[0])}
              style={{ flex: 1, textAlign: "center", padding: "10px 8px", borderRadius: 6, border: "2px solid " + (depth === d[0] ? C.accent : C.border), background: depth === d[0] ? C.accentLight : C.surface, cursor: "pointer" }}>
              <div style={{ fontSize: 13, fontWeight: 700, color: depth === d[0] ? C.accent : C.textPrimary }}>{d[1]}</div>
              <div style={{ fontSize: 11, color: C.textMuted }}>{d[2]}</div>
            </div>
          ))}
        </div>
      </Box>

      <Btn primary full disabled={!canRun} onClick={() => onRun({ url, code, mode, types, depth })}>
        🚀 Launch AI Test Suite
      </Btn>
    </div>
  );
}

// ── RUNNING ───────────────────────────────────────────────────
const RUN_STEPS = [
  ["info", "Connecting to target application"],
  ["info", "Crawling routes — 24 pages found"],
  ["info", "AI generating 418 test cases"],
  ["pass", "✓ Homepage loads under 1.2s"],
  ["pass", "✓ Login form validates correctly"],
  ["pass", "✓ Checkout flow completes end-to-end"],
  ["fail", "✗ Security: SQL injection on /search"],
  ["fail", "✗ Security: No rate limiting on login"],
  ["pass", "✓ Performance: LCP 1.4s (Good)"],
  ["warn", "⚠ Performance: /dashboard 3.2s under load"],
  ["pass", "✓ Mobile: all 54 viewport tests pass"],
  ["fail", "✗ Unit: hashPassword() accepts empty string"],
  ["info", "⟳ Self-healing: 4 selectors auto-repaired"],
  ["pass", "✓ 401 passed · 17 bugs found"],
  ["info", "Compiling report..."],
];

const RUN_PHASES = ["Initialising...", "Crawling app...", "Generating tests...", "Running browser tests...", "Running security audit...", "Running performance tests...", "Finalising report..."];

function Running({ onDone }) {
  const [progress, setProgress] = useState(0);
  const [log, setLog] = useState([]);
  const [phase, setPhase] = useState("Initialising AI engines...");

  const steps = RUN_STEPS;
  const phases = RUN_PHASES;

  useEffect(() => {
    let i = 0;
    const t = setInterval(() => {
      if (i >= steps.length) { clearInterval(t); setTimeout(onDone, 500); return; }
      setLog((l) => [...l, steps[i]]);
      setProgress(Math.round((i / steps.length) * 100));
      setPhase(phases[Math.min(phases.length - 1, Math.floor((i / steps.length) * phases.length))]);
      i++;
    }, 420);
    return () => clearInterval(t);
  }, []);

  const lc = { info: C.textSecondary, pass: C.green, fail: C.red, warn: C.yellow };

  return (
    <div style={{ maxWidth: 620, margin: "0 auto", padding: "56px 28px", textAlign: "center" }}>
      <div style={{ fontSize: 52, marginBottom: 16 }}>🤖</div>
      <h2 style={{ fontSize: 24, fontWeight: 900, color: C.textPrimary, marginBottom: 6 }}>AI is Auditing Your App</h2>
      <p style={{ fontSize: 14, color: C.textSecondary, marginBottom: 24 }}>{phase}</p>
      <div style={{ marginBottom: 6 }}><Bar value={progress} height={8} /></div>
      <p style={{ fontSize: 12, color: C.textMuted, marginBottom: 28 }}>{progress}% complete</p>
      <Box style={{ textAlign: "left", maxHeight: 290, overflowY: "auto", fontFamily: "monospace" }}>
        {log.filter((l) => Array.isArray(l) && l.length >= 2).map((l, i) => (
          <div key={i} style={{ fontSize: 12, color: lc[l[0]] || C.textSecondary, padding: "4px 0", borderBottom: "1px solid " + C.bg }}>
            <span style={{ color: C.textMuted, marginRight: 8 }}>{String(i + 1).padStart(2, "0")}</span>{l[1]}
          </div>
        ))}
      </Box>
    </div>
  );
}

// ── RESULTS ───────────────────────────────────────────────────
function Results({ onReset }) {
  const [tab, setTab] = useState("overview");
  const [sel, setSel] = useState(null);

  const bugs = [
    { id: "SEC-001", sev: "critical", cat: "Security", title: "SQL Injection on /search", desc: "User input passed into raw SQL. Attacker can dump full database.", fix: "db.query('SELECT * FROM items WHERE name = ?', [input])", file: "api/search.js:34", cvss: 9.8 },
    { id: "SEC-002", sev: "high", cat: "Security", title: "No rate limiting on /api/auth/login", desc: "Login allows unlimited attempts — brute force possible.", fix: "Add express-rate-limit: 5 requests / 15 min per IP.", file: "routes/auth.js:12", cvss: 7.5 },
    { id: "PERF-001", sev: "medium", cat: "Performance", title: "/dashboard responds 3.2s under load", desc: "N+1 query in getUserData() causes slowdown.", fix: "Use Promise.all() for parallel queries. Add Redis cache.", file: "api/dashboard.js:67", cvss: null },
    { id: "UNIT-001", sev: "medium", cat: "Unit", title: "hashPassword() accepts empty string", desc: "Empty string returns valid hash — auth vulnerability.", fix: "if (!password) throw new Error('Password required');", file: "utils/auth.js:18", cvss: 6.1 },
    { id: "SEC-003", sev: "low", cat: "Security", title: "Server version in response headers", desc: "X-Powered-By: Express leaks stack info.", fix: "app.disable('x-powered-by')", file: "app.js:5", cvss: 3.1 },
  ];

  const sc = { critical: "#ff3c00", high: "#f97316", medium: "#ffbe00", low: "#0057ff" };

  const suites = [
    { name: "Browser Automation", icon: "🤖", total: 186, passed: 183, failed: 3 },
    { name: "Security / Pen Test", icon: "🔒", total: 94, passed: 91, failed: 3 },
    { name: "Load & Performance", icon: "⚡", total: 72, passed: 71, failed: 1 },
    { name: "Unit Tests", icon: "🧩", total: 42, passed: 41, failed: 1 },
    { name: "Mobile Simulation", icon: "📱", total: 54, passed: 54, failed: 0 },
  ];

  const healing = [
    { test: "checkout.placeOrderBtn", reason: "Selector #place-order renamed to [data-action='submit-order']", confidence: 96 },
    { test: "auth.forgotPasswordLink", reason: "Link moved from header to footer", confidence: 91 },
    { test: "profile.saveButton", reason: "Button now inside shadow DOM", confidence: 85 },
    { test: "search.filterDropdown", reason: "Radix UI replaced native select", confidence: 79 },
  ];

  const bug = sel !== null ? bugs[sel] : null;

  return (
    <div style={{ maxWidth: 980, margin: "0 auto", padding: "32px 28px" }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 28 }}>
        <div>
          <Tag label="Audit Complete" color={C.green} />
          <h2 style={{ fontSize: 26, fontWeight: 900, color: C.textPrimary, margin: "8px 0 4px" }}>Full Audit Report</h2>
          <p style={{ fontSize: 13, color: C.textSecondary }}>418 tests · 2m 41s · AI-generated</p>
        </div>
        <div style={{ display: "flex", gap: 8 }}>
          <Btn small onClick={onReset}>← New Audit</Btn>
          <Btn small primary>⬇ Export PDF</Btn>
        </div>
      </div>

      {/* Score cards */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(5, 1fr)", gap: 12, marginBottom: 28 }}>
        {[["418", "Tests Run", C.textPrimary], ["401", "Passed", C.green], ["17", "Failed", C.red], ["5", "Bugs", C.yellow], ["4", "Auto-Healed", C.blue]].map((item) => (
          <Box key={item[1]} style={{ textAlign: "center", padding: "16px 10px" }}>
            <div style={{ fontSize: 28, fontWeight: 900, color: item[2] }}>{item[0]}</div>
            <div style={{ fontSize: 11, color: C.textSecondary, marginTop: 4, fontWeight: 600 }}>{item[1]}</div>
          </Box>
        ))}
      </div>

      {/* Tabs */}
      <div style={{ display: "flex", gap: 4, borderBottom: "2px solid " + C.border, marginBottom: 24 }}>
        {["overview", "bugs", "suites", "healing"].map((k) => (
          <button key={k} onClick={() => setTab(k)}
            style={{ background: tab === k ? C.textPrimary : "transparent", color: tab === k ? "#fff" : C.textSecondary, border: "2px solid " + C.border, borderBottom: tab === k ? "2px solid " + C.textPrimary : "2px solid transparent", padding: "9px 18px", fontSize: 13, fontWeight: 700, cursor: "pointer", fontFamily: "inherit", marginRight: 4, borderRadius: "6px 6px 0 0", marginBottom: -2 }}>
            {k.charAt(0).toUpperCase() + k.slice(1)}
          </button>
        ))}
      </div>

      {tab === "overview" && (
        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          <Box>
            <div style={{ fontSize: 13, fontWeight: 800, color: C.textMuted, marginBottom: 14, textTransform: "uppercase" }}>Health Score</div>
            <div style={{ display: "flex", alignItems: "center", gap: 20 }}>
              <div style={{ width: 76, height: 76, borderRadius: "50%", border: "4px solid " + C.yellow, background: C.yellowLight, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
                <span style={{ fontSize: 24, fontWeight: 900, color: "#7a5a00" }}>68</span>
              </div>
              <div style={{ flex: 1 }}>
                {[["Security", 42, C.red], ["Performance", 76, C.yellow], ["Functionality", 96, C.green], ["Mobile", 100, C.green]].map((item) => (
                  <div key={item[0]} style={{ marginBottom: 8 }}>
                    <div style={{ display: "flex", justifyContent: "space-between", fontSize: 12, marginBottom: 3 }}>
                      <span style={{ color: C.textSecondary, fontWeight: 600 }}>{item[0]}</span>
                      <span style={{ color: item[2], fontWeight: 800 }}>{item[1]}%</span>
                    </div>
                    <Bar value={item[1]} color={item[2]} height={5} />
                  </div>
                ))}
              </div>
            </div>
          </Box>
          <Box>
            <div style={{ fontSize: 13, fontWeight: 800, color: C.textMuted, marginBottom: 10, textTransform: "uppercase" }}>AI Summary</div>
            <div style={{ fontSize: 14, color: C.textPrimary, lineHeight: 1.75, background: C.bg, borderRadius: 6, padding: "14px 16px", border: "1px solid " + C.border }}>
              <strong style={{ color: C.red }}>CRITICAL:</strong> SQL injection on /search — patch before deployment. {" "}
              <strong style={{ color: "#f97316" }}>HIGH:</strong> Login has no rate limiting — brute force risk. {" "}
              <strong style={{ color: C.green }}>POSITIVE:</strong> Core functionality and mobile are excellent (96–100%).
            </div>
          </Box>
        </div>
      )}

      {tab === "bugs" && (
        <div style={{ display: "flex", gap: 16 }}>
          <div style={{ flex: 1, display: "flex", flexDirection: "column", gap: 10 }}>
            {bugs.map((b, i) => (
              <Box key={b.id} style={{ cursor: "pointer", border: "2px solid " + (sel === i ? sc[b.sev] : C.border) }}
                onClick={() => setSel(i === sel ? null : i)}>
                <div style={{ display: "flex", gap: 8, marginBottom: 6, flexWrap: "wrap" }}>
                  <Tag label={b.sev} color={sc[b.sev]} />
                  <Tag label={b.cat} color={C.textMuted} />
                  {b.cvss && <Tag label={"CVSS " + b.cvss} color={b.cvss >= 9 ? C.red : b.cvss >= 7 ? "#f97316" : C.yellow} />}
                </div>
                <div style={{ fontSize: 14, fontWeight: 700, color: C.textPrimary }}>{b.title}</div>
                <div style={{ fontSize: 12, color: C.textMuted, marginTop: 4, fontFamily: "monospace" }}>{b.file}</div>
              </Box>
            ))}
          </div>
          {bug && (
            <div style={{ width: 300, flexShrink: 0 }}>
              <Box style={{ border: "2px solid " + sc[bug.sev] }}>
                <div style={{ display: "flex", gap: 6, marginBottom: 12 }}>
                  <Tag label={bug.sev} color={sc[bug.sev]} />
                  <Tag label={bug.cat} color={C.textMuted} />
                </div>
                <div style={{ fontSize: 14, fontWeight: 800, color: C.textPrimary, marginBottom: 8 }}>{bug.title}</div>
                <div style={{ fontSize: 12, color: C.textSecondary, lineHeight: 1.65, marginBottom: 14 }}>{bug.desc}</div>
                <div style={{ fontSize: 11, fontWeight: 800, color: C.green, marginBottom: 6, textTransform: "uppercase" }}>AI Fix</div>
                <div style={{ fontSize: 12, color: C.textPrimary, background: C.bg, borderRadius: 4, padding: "10px 12px", fontFamily: "monospace", lineHeight: 1.6, border: "1px solid " + C.border }}>{bug.fix}</div>
              </Box>
            </div>
          )}
        </div>
      )}

      {tab === "suites" && (
        <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
          {suites.map((s) => (
            <Box key={s.name}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10 }}>
                <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                  <span style={{ fontSize: 22 }}>{s.icon}</span>
                  <span style={{ fontSize: 15, fontWeight: 700, color: C.textPrimary }}>{s.name}</span>
                </div>
                <div style={{ display: "flex", gap: 16, fontSize: 13 }}>
                  <span style={{ color: C.green, fontWeight: 700 }}>✓ {s.passed}</span>
                  <span style={{ color: s.failed > 0 ? C.red : C.textMuted, fontWeight: 700 }}>✗ {s.failed}</span>
                </div>
              </div>
              <Bar value={Math.round((s.passed / s.total) * 100)} color={s.failed > 0 ? C.yellow : C.green} height={6} />
              <div style={{ fontSize: 12, color: C.textMuted, marginTop: 6 }}>{s.total} tests · {Math.round((s.passed / s.total) * 100)}% pass rate</div>
            </Box>
          ))}
        </div>
      )}

      {tab === "healing" && (
        <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
          <Box>
            <div style={{ fontSize: 13, fontWeight: 800, color: C.textMuted, marginBottom: 14, textTransform: "uppercase" }}>4 Tests Repaired Automatically</div>
            {healing.map((h, i) => (
              <div key={i} style={{ background: C.bg, borderRadius: 6, padding: "12px 14px", marginBottom: 10, border: "1px solid " + C.border }}>
                <div style={{ fontSize: 13, fontWeight: 700, color: C.textPrimary, fontFamily: "monospace", marginBottom: 4 }}>{h.test}</div>
                <div style={{ fontSize: 12, color: C.textSecondary, marginBottom: 10 }}>{h.reason}</div>
                <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                  <span style={{ fontSize: 11, fontWeight: 700, color: C.textMuted }}>Confidence</span>
                  <div style={{ flex: 1 }}><Bar value={h.confidence} color={h.confidence >= 85 ? C.green : C.yellow} height={5} /></div>
                  <span style={{ fontSize: 12, fontWeight: 800, color: h.confidence >= 85 ? C.green : C.yellow }}>{h.confidence}%</span>
                </div>
              </div>
            ))}
          </Box>
          <Box>
            <div style={{ fontSize: 13, fontWeight: 800, color: C.textMuted, marginBottom: 10, textTransform: "uppercase" }}>Time Saved</div>
            <p style={{ fontSize: 15, color: C.textPrimary, lineHeight: 1.7 }}>
              These 4 tests would take a developer <strong style={{ color: C.green }}>45–60 minutes</strong> to fix manually. QualityZero repaired them in under <strong>8 seconds</strong>.
            </p>
          </Box>
        </div>
      )}
    </div>
  );
}

// ── ROOT APP ──────────────────────────────────────────────────
export default function App() {
  const [page, setPage] = useState("landing");
  const [config, setConfig] = useState(null);

  return (
    <div style={{ background: C.bg, minHeight: "100vh", fontFamily: "'Inter', system-ui, sans-serif", color: C.textPrimary }}>
      <style>{`* { box-sizing: border-box; margin: 0; padding: 0; } ::-webkit-scrollbar { width: 6px; } ::-webkit-scrollbar-thumb { background: #ccc; border-radius: 99px; }`}</style>
      <Navbar setPage={setPage} />
      {page === "landing" && <Landing onStart={() => setPage("run")} />}
      {page === "run" && <Configure onRun={(cfg) => { setConfig(cfg); setPage("running"); }} />}
      {page === "running" && <Running config={config} onDone={() => setPage("results")} />}
      {page === "results" && <Results onReset={() => setPage("run")} />}
    </div>
  );
}